@token = G4jJLY5czAgNItrBAFlmKAgfIDyXqAbGsVDo432k4q8=
@token2 = OmZjdyvgEhrgpjqj-r2KjaqUtp193HZCguMdr-SQNfE=


// http://localhost:8080/oauth2/authorization/github   login with github
// http://localhost:8080/oauth2/authorization/google   login with google
// http://localhost:8080/oauth2/authorization/gitlab   login with gitlab
// http://localhost:8080/oauth2/authorization/github-api   authorize with github for api access

// http://localhost:8080/github/repositories/{rid}/dependabot
// http://localhost:8080/github/repos/RodrigoVitorino

### internal register
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "testeUserSemRepos",
  "password": "teste1",
  "email": "testeUserSemRepos@test.com"
}


### internal login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "testeUserSemRepos",
  "password": "teste1"
}

### user profile
GET http://localhost:8080/users/me
Authorization: Bearer {{token}}


### add repository
POST http://localhost:8080/github/repositories
Authorization: Bearer {{token2}}
Content-Type: application/json

{
  "name": "RodrigoVitorino/secdash-sast-test"
}

### add another repository
POST http://localhost:8080/github/repositories
Authorization: Bearer {{token2}}
Content-Type: application/json

{
  "name": "RodrigoVitorino/SecDash-test"
}



### add gitlab repository
POST http://localhost:8080/gitlab/repositories
Authorization: Bearer {{token2}}
Content-Type: application/json

{
  "externalId": "80319756"
}


### add another gitlab repo
POST http://localhost:8080/gitlab/repositories
Authorization: Bearer {{token2}}
Content-Type: application/json

{
  "externalId": "80515032"
}