@token = Dnel-1BUdlaqTl8EZX3ssFeZ5gYmBNdLhKR-fzaa74k=
@token2 = L4qpphfAASawgidFuuRDXSebHCZUZ2Eegz5BjkdOOj4=


// http://localhost:8080/oauth2/authorization/github   login with github
// http://localhost:8080/oauth2/authorization/google   login with google
// http://localhost:8080/oauth2/authorization/github-api   authorize with github for api access


### internal register
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "teste1",
  "password": "teste1",
  "email": "email1"
}


### internal login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "teste1",
  "password": "teste1"
}

### user profile
GET http://localhost:8080/users/me
Authorization: Bearer {{token2}}


### add repository
POST http://localhost:8080/github/repositories
Authorization: Bearer {{token2}}
Content-Type: application/json

{
  "name": "RodrigoVitorino/secdash-sast-test"
}

### add another repository
POST http://localhost:8080/github/repositories
Authorization: Bearer {{token2}}
Content-Type: application/json

{
  "name": "RodrigoVitorino/SecDash-test"
}