@token = Dnel-1BUdlaqTl8EZX3ssFeZ5gYmBNdLhKR-fzaa74k=
@token2 =

###
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "teste1",
  "password": "teste1",
  "email": "email1"
}


###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "teste1",
  "password": "teste1"
}

###
GET http://localhost:8080/users/me
Authorization: Bearer {{token}}