@token = x3DFRkQ5pYd5YfBpFNMy3sFOZm-_bBbIMZIp4x-Ysqk=


// http://localhost:8080/oauth2/authorization/github   login with github

// http://localhost:8080/oauth2/authorization/github-api   authorize with github for api access

// http://localhost:8080/github/repos

### create a new user
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "testeteste",
  "password": "testestestes",
  "email": "teste@testes"
}

### create another user
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "testetesteas",
  "password": "testestestesas",
  "email": "teste@testesas"
}

### login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "testeteste",
  "password": "testestestes"
}

### add github dependabot repository
POST http://localhost:8080/github/repositories
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "RodrigoVitorino/SecDash-test"
}


### add github sast repository
POST http://localhost:8080/github/repositories
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "RodrigoVitorino/secdash-sast-test"
}

###
// http://localhost:8080/oauth2/authorization/gitlab-api  authorize with gitlab for api access

// http://localhost:8080/gitlab/repos



### add dependancy-scanning gitlab repository
POST http://localhost:8080/gitlab/repositories
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "externalId": "80319756"
}


### add sast gitlab repo
POST http://localhost:8080/gitlab/repositories
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "externalId": "80515032"
}


### Github dependabot
GET http://localhost:8080/github/repositories/1/dependabot
Authorization: Bearer {{token}}
Content-Type: application/json


### Gitlab dependancy-scanning
GET http://localhost:8080/gitlab/repositories/3/dependency-scanning
Authorization: Bearer {{token}}

### Github sast
GET http://localhost:8080/github/repositories/2/sast
Authorization: Bearer {{token}}
Content-Type: application/json

### Gitlab sast
GET http://localhost:8080/gitlab/repositories/4/sast
Authorization: Bearer {{token}}


### Create new team
POST http://localhost:8080/teams
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "grandaEquipa",
  "description": "testes"
}

### Create another team
POST http://localhost:8080/teams
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "grandaEquipa2",
  "description": "testes2"
}

### User Profile information
GET http://localhost:8080/users/me
Authorization: Bearer {{token}}

### Get the list of Teams of the User Logged in
GET http://localhost:8080/teams
Authorization: Bearer {{token}}

### get team information
GET http://localhost:8080/teams/1
Authorization: Bearer {{token}}

### Delete a Team
DELETE http://localhost:8080/teams/2
Authorization: Bearer {{token}}

### Add user to team
POST http://localhost:8080/teams/1/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": 2
}

### remove user from team
DELETE http://localhost:8080/teams/1/users/2
Authorization: Bearer {{token}}

### promote user to team leader
PATCH http://localhost:8080/teams/1/users/2
Authorization: Bearer {{token}}

### add repository to team
POST http://localhost:8080/teams/1/repository
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "repositoryId": 1
}

### remove repository from a team
DELETE http://localhost:8080/teams/1/repository/1
Authorization: Bearer {{token}}
