spring.application.name=secdash
frontend.url=${FRONTEND_URL:http://localhost:5173}
app.gitlab.redirect-uri=${GITLAB_REDIRECT_URI:http://localhost:8080/login/oauth2/code/gitlab}
server.port=${port:8080}

spring.config.import=optional:file:.env[.properties]

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

spring.security.oauth2.client.registration.github-api.provider=github
spring.security.oauth2.client.registration.github-api.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github-api.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github-api.scope=repo,security_events
spring.security.oauth2.client.registration.github-api.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.github-api.redirect-uri={baseUrl}/login/oauth2/code/github

spring.security.oauth2.client.registration.gitlab.client-id=${GITLAB_CLIENT_ID}
spring.security.oauth2.client.registration.gitlab.client-secret=${GITLAB_CLIENT_SECRET}
spring.security.oauth2.client.registration.gitlab.scope=read_user
spring.security.oauth2.client.registration.gitlab.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.gitlab.redirect-uri={baseUrl}/login/oauth2/code/gitlab

spring.security.oauth2.client.registration.gitlab-api.provider=gitlab
spring.security.oauth2.client.registration.gitlab-api.client-id=${GITLAB_CLIENT_ID}
spring.security.oauth2.client.registration.gitlab-api.client-secret=${GITLAB_CLIENT_SECRET}
spring.security.oauth2.client.registration.gitlab-api.scope=api
spring.security.oauth2.client.registration.gitlab-api.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.gitlab-api.redirect-uri={baseUrl}/login/oauth2/code/gitlab

spring.security.oauth2.client.provider.gitlab.authorization-uri=https://gitlab.com/oauth/authorize
spring.security.oauth2.client.provider.gitlab.token-uri=https://gitlab.com/oauth/token
spring.security.oauth2.client.provider.gitlab.user-info-uri=https://gitlab.com/api/v4/user
spring.security.oauth2.client.provider.gitlab.user-name-attribute=username

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG


